version: "3"
services:
  postgre-quiz-lore:
    image: postgis/postgis
    container_name: 'postgre-ql'
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      PGDATA: "/var/lib/postgresql/data/pgdata"
      LANG: "C"
      LC_CTYPE: "C"
      LC_COLLATE: "C"
    expose:
      - "5433"
    volumes:
      - ./psql-ext.sql:/docker-entrypoint-initdb.d/psql_ext.sql
      - .:/var/lib/postgresql/data
    ports:
      - "5433:5433"
    command: -p 5433
    restart: unless-stopped
    healthcheck:
      test: [ 'CMD', 'pg_isready -U test' ]
      interval: 5s
      timeout: 5s
      retries: 5

  quiz-lore-auth:
    image: registry.supertokens.io/supertokens/supertokens-postgresql
    container_name: 'auth-ql'
    depends_on:
      - postgre-quiz-lore
    environment:
      POSTGRESQL_USER: "test"
      POSTGRESQL_PASSWORD: "test"
      POSTGRESQL_HOST: "postgre-ql"
      POSTGRESQL_PORT: "5433"
      POSTGRESQL_DATABASE_NAME: "test"
      POSTGRESQL_TABLE_SCHEMA: "auth"
      API_KEYS: 'meJilFQL20FnWMaPWIy9N3dpbdMxi1Sa'
    expose:
      - 3568
    ports:
      - 3568:3567
    restart: unless-stopped
    healthcheck:
      test: >
        bash -c 'exec 3<>/dev/tcp/127.0.0.1/3568 && echo -e "GET /hello HTTP/1.1\r\nhost: 127.0.0.1:3568\r\nConnection: close\r\n\r\n" >&3 && cat <&3 | grep "Hello"'
      interval: 10s
      timeout: 5s
      retries: 5
